export const AIQ_THEME_APPEARANCE = "AIQ_THEME_APPEARANCE";

export const AIQ_THEME_PRIMARY_COLOR = "AIQ_THEME_PRIMARY_COLOR";

export const AIQ_THEME_NEUTRAL_COLOR = "AIQ_THEME_NEUTRAL_COLOR";

export const AI_SERVICE_PROVIDERS_ICON_SIZE = 32;